export const GET_DELIVERIES_LIST_STARTED = 'GET_DELIVERIES_LIST_STARTED';
export const GET_DELIVERIES_LIST_SUCCESS = 'GET_DELIVERIES_LIST_SUCCESS';
export const GET_DELIVERIES_LIST_ERROR = 'GET_DELIVERIES_LIST_ERROR';


export const DELIVERY_DETAILS_STARTED = 'DELIVERY_DETAILS_STARTED';
export const DELIVERY_DETAILS_SUCCESS = 'DELIVERY_DETAILS_SUCCESS';
export const DELIVERY_DETAILS_ERROR = 'DELIVERY_DETAILS_ERROR';


export const MARK_DELIVERY_ACTIVE = 'MARK_DELIVERY_ACTIVE';
export const CHANGE_DELIVERY_STATUS_STARTED = 'CHANGE_DELIVERY_STATUS_STARTED';
export const CHANGE_DELIVERY_STATUS_SUCCESS = 'CHANGE_DELIVERY_STATUS_SUCCESS';
export const CHANGE_DELIVERY_STATUS_ERROR = 'CHANGE_DELIVERY_STATUS_ERROR';